MODBUS_HOST = "localhost"
MODBUS_IP = "127.0.0.1" 
MODUBS_PORT= 8889
MODBUS_UNIT_ID=1
NMEA_HOST="localhost"
NMEA_PORT=8888
MIN_TEMPERATURE_CHANGE=1 #C
MIN_ELAPSED_TIME = 5 #mins
MIN_ROT_CHANGE=1 #degrees
MQTT_BROKER_HOST="a7fb406d74d6425f98e1bb4b6da01446.s1.eu.hivemq.cloud"
MQTT_BROKER_PORT=8883
MQTT_BROKER_USERNAME=None # credentials are in the email body
MQTT_BROKER_PASSWORD=None # credentials are in the email body
MAX_ELAPSED_TIME = 10 # Max elapsed time of inactivity in minutes
